name: maple_harvest_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  connectivity_plus: ^6.1.0
  logger: ^2.4.0
  firebase_core: ^3.6.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  easy_localization: ^3.0.7
  get_it: ^8.0.0
  firebase_analytics: ^11.3.3
  google_fonts: ^6.2.1
  go_router: ^14.3.0
  flutter_hooks: ^0.20.5
  flutter_native_splash: ^2.4.2
  flutter_svg: ^2.0.10+1
  loading_indicator: ^3.1.1
  graphql_flutter: ^5.2.0-beta.7
  tap_debouncer: ^2.2.0
  collection: ^1.18.0
  path_provider: ^2.1.5
  firebase_crashlytics: ^4.1.4
  email_validator: ^3.0.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.3
  fluttertoast: ^8.2.8
  permission_handler: ^11.3.1
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  recase: ^4.1.0
  animated_bottom_navigation_bar:
    git:
      url: https://github.com/zeeshanahmad0201/animated-bottom-navigation-bar-flutter.git
      ref: fix/center-fab-location
  dio: ^5.7.0
  location: ^7.0.1
  gql: ^1.0.1-alpha+1730759315362
  sqflite: ^2.4.1
  path: ^1.9.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  firebase_core_platform_interface: ^5.3.0
  flutter_dotenv: ^5.2.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/translations/
    - assets/images/

flutter_assets_generator:
  output_dir: core/config
  output_filename: assets

flutter_native_splash:
  background_image: assets/images/splash_bg.png
  android_12:
    image: assets/images/splash_logo.png
    color: "#FF0101"
  # iOS is managed manually so need to set this to true
  ios: false
  android: true
  web: false
