///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesAlertDot = 'assets/images/alert_dot.png';
  static const String imagesAppIcon = 'assets/images/app_icon.png';
  static const String imagesBlackIconLoc = 'assets/images/black_icon_loc.png';
  static const String imagesCart = 'assets/images/cart.png';
  static const String imagesDropDownIcon = 'assets/images/drop_down_icon.svg';
  static const String imagesFavorite = 'assets/images/favorite.png';
  static const String imagesHome = 'assets/images/home.png';
  static const String imagesInfoAlert = 'assets/images/info_alert.png';
  static const String imagesList = 'assets/images/list.png';
  static const String imagesLocateMe = 'assets/images/locate_me.svg';
  static const String imagesLocateme = 'assets/images/locateme.svg';
  static const String imagesLocationIcon = 'assets/images/location_icon.svg';
  static const String imagesLogo = 'assets/images/logo.png';
  static const String imagesMic = 'assets/images/mic.png';
  static const String imagesNotificationIcon = 'assets/images/notification-icon.svg';
  static const String imagesOnboarding1 = 'assets/images/onboarding_1.png';
  static const String imagesOnboarding2 = 'assets/images/onboarding_2.png';
  static const String imagesSplashBg = 'assets/images/splash_bg.png';
  static const String imagesSplashLogo = 'assets/images/splash_logo.png';
  static const String imagesTest = 'assets/images/test.svg';
  static const String imagesUser = 'assets/images/user.png';
  static const String mapleHarvestApp = '.env';
  static const String translationsEn = 'assets/translations/en.json';

}
